#!/usr/bin/env groovy

pipeline {

    agent any

    parameters {
        string(name: 'git_branch', defaultValue: 'origin/develop', description: 'Git branch to checkout')
    }

    stages {

        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -B test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

    }
}
